name: vain_ui
description: An UI toolkit highly inspired from the Carbon Design System. Contains custom widgets for most usecases.
version: 0.1.0
homepage:


environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/test.svg
    - assets/bouncing_ball.riv
    - assets/svg/checkmark--filled.svg
    - assets/svg/checkmark.svg
    - assets/svg/toggle-checkmark.svg
    - assets/svg/warning--alt--filled.svg
    - assets/svg/warning--filled.svg
    - assets/svg/line.svg

  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexSans-Thin.ttf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic
